### ISSUE TITLE
User to unsubscribe when #149 is ready

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#188]
### Expected Behaviour

Users to be unsubscribed : 
user n°22625 (b****.*****a@*****.com) 
user n°21970 (i....@......b.com)
user n°23540 (l****c@*****.com)

Thanks Hook

**Comment by MathieuNls** [comment]
#149 isn t merged. I can delete him, that's all

**Comment by AlphonseJr** [comment]
I know, I'm just logging in the defect for when #149 will be merged !

**Comment by MathieuNls** [comment]
Ok, don't open a new issue of each one, though. Add them here.

**Comment by AlphonseJr** [comment]
It's a better idea indeed ;) I'll do that!

**Comment by MathieuNls** [comment]
Done
