### ISSUE TITLE
Mobile display of the webapp

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#190]
### Expected Behaviour
*The homage should be displayed without any distorsion*

### Actual Behaviour
*We have a regression where the homepage is not displayed in a distorted way* : 

![image](https://cloud.githubusercontent.com/assets/6577742/20239673/1d97d754-a906-11e6-9007-0d465dd9207a.png)

*Also, when I pinch down the image, I can see this (which I suppose should be hidden)* : 

![image](https://cloud.githubusercontent.com/assets/6577742/20239683/5c11a5a0-a906-11e6-8a9e-bc53efe58d00.png)

Both behaviors are recent.

###### Steps to reproduce the actual behaviour
* Go on the homepage (chrome on iPhone 5s)

Thanks Hook!

**Comment by MathieuNls** [comment]
That's the behavior now. 

![untitled](https://cloud.githubusercontent.com/assets/7218861/20239705/af0c7384-a8d4-11e6-89eb-d8f0f8db3ec5.png)

For a short moment, yesterday, it might have been like your screenshot. See #deploy channel. 
Moreover, I won't invest time here before a complete redesign.

**Comment by AlphonseJr** [comment]
Great! It wasn't working this morning with @VS2000 but not everything is back to normal, thanks!
