### ISSUE TITLE
Display of the accuracy ranking

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#191]
### Expected Behaviour
*After a measure, the user should see a ranking of his result as we used to have*

### Actual Behaviour
![image](https://cloud.githubusercontent.com/assets/6577742/20543720/3676f7c4-b107-11e6-9abc-94508103bfb2.png)

Thanks Hook

**Comment by MathieuNls** [comment]
Fixed by 40ca62308e9a8074a279ddcae80221940b174ec0
