### ISSUE TITLE
Meta description update

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#201]
### Expected Behaviour
*New meta description of the homepage should be:*
``Measure and track the accuracy of your mechanical watch. Free watch accuracy app also available for iOS and Android.``

Thanks!

**Comment by MathieuNls** [comment]
Is that for the title or the description. Current values are

- `title`: Toolwatch - Easily measure and track the accuracy of your mechanical watch
- `description`: Toolwatch makes it super easy to measure the accuracy of a mechanical watch. Keep your watch\'s accuracy at its best and know if you should service your watch

**Comment by AlphonseJr** [comment]
I've written "meta description", it's for the description hehe
