### ISSUE TITLE
Display on Kindle Fire

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#206]
### Expected Behaviour
*The display of the Toolwatch website should be as perfect as possible on any given (common!) device. We have received a message from a user asking an improvement of the rendering on Kindle Fire*

### Actual Behaviour
*Here is the message of the user along with the screenshots :*

> Thank you for providing this app. I use a kindle HD in landscape orientation. The banner at the top of the page takes up appropriately one-half the screen, with no way to size it. Turing the kindle to a portrait/vertical orientation, you display a 'down/up-arrow' to expand/collapse the banner. However, it is very inconvenient for the user in this orientation. 

And the screenshots : 
![toolwatch_dscn0938](https://cloud.githubusercontent.com/assets/6577742/21581971/99cbb0a8-d047-11e6-9d63-9ffb7e217ee1.JPG)
![toolwatch_dscn0937](https://cloud.githubusercontent.com/assets/6577742/21581974/9a26260a-d047-11e6-9908-95a4d0c8a0b5.JPG)
![toolwatch_dscn0936](https://cloud.githubusercontent.com/assets/6577742/21581975/9a7093b6-d047-11e6-8fdd-677011cc2858.JPG)
![toolwatch_dscn0935](https://cloud.githubusercontent.com/assets/6577742/21581972/99cd3cb6-d047-11e6-9255-b7a6551e8b61.JPG)
![toolwatch_dscn0934](https://cloud.githubusercontent.com/assets/6577742/21581973/99df2142-d047-11e6-8d57-88dc1aa80f42.JPG)

Thanks Hook!

(Never would have thought that we are popular on Kindle Fire too!)

**Comment by MathieuNls** [comment]
Pending complete redesign.

**Comment by AlphonseJr** [comment]
That's what I thought as well, I've logged it just in case it was a tiny fix that could've been done in the meantime.
2017 will see a new Toolwatch design !!
