### ISSUE TITLE
Improvement of the clock displayed

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#215]
### Expected Behaviour
*Some users are complaining on the accuracy of the clock displayed on the dashboard (or on the Time screen on mobile) as this is not an atomic clock. Even though it has no interference with the actual accuracy of the Toolwatch system, this might still be confusing. Would it be possible to retrieve a clock from a reliable source such as this one? http://time.gov/widget/ What are your thoughts on that?*

Thanks Hook!

**Comment by MathieuNls** [comment]
It is an atomic clock in a sense that is synced with one with network latency mitigation. 
This clock is the result of the same processes as the ones I described here: https://toolwatch.io/about.

I don't dismiss the presence of a bug there, but the source data is more accurate than  http://time.gov/widget/.
