### ISSUE TITLE
Question : mapping fields from Facebook

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#218]
Hi Hook!

I had a question : could you please check that users subscribing from Facebook have their names correctly saved with "First Name" not being mistaken with "Last Name"?

I see quite a few generic mails from users where we are switching their first with their last name and as some a native us speakers, I doubt they entered them incorrectly, my guess is that the fields mapping when using Facebook is wrong.

Thanks!

**Comment by MathieuNls** [comment]
Yes, lastname and firstname used to be switched in earlier version of the mobile app. It has been fixed a while ago. 

New facebook accounts created from the mobile apps should be ok.
