### ISSUE TITLE
Embed SDK of our shop on mobile app.

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#220]
As per our latest meeting, I'm adding here for reference our need of replacing the "About" button on our mobile app footer by a "Shop" button linking to our future shop.

As this is a "sensitive" project in the sense that we haven't revealed it yet to our users, I'll let Hook decide the best way to communicate on this topic! (github or slack)

In the meantime, we will be able to launch by adding a link to the shop in the header of the webapp.

Thanks

**Comment by MathieuNls** [comment]
That's a mobile feature request.
