### ISSUE TITLE
Question: how accuracy is computed?

### ISSUE THREAD

**Issue by ldmpub** [Toolwatchapp/tw-backend#229]
Hi,

This is not a bug (yet?) but rather a question: how accuracy is computed? Is there any "public" algorithm I can look at to understand the measures displayed both in the web site and in the mobile app?

From my point of view, results currently displayed are strange / erroneous and because as a user I don't have access to any of my measures, I can not trust ToolWatch (despite the time I have spent to perform more than 8 measures so far).

Thanks in advance for your answer,

**Comment by MathieuNls** [comment]
Hi @ldmpub ,

_This is not a bug (yet?) but rather a question: how accuracy is computed? Is there any "public" algorithm I can look at to understand the measures displayed both in the web site and in the mobile app?_

In english, you can find it here https://toolwatch.io/about/.

If you are here for a more techie answer, then, you the actual accuracy is computed here: https://github.com/Toolwatchapp/tw-backend/blob/master/application/models/Measure.php#L184

The line you are probably after is the following:

```php
$accuracy = ($userDelta!=0) ? ($refDelta*86400/$userDelta)-86400 : 0;
```

`userDelta` and `refDelta` are the deltas computed for both measures you do on toolwatch. `userDelta` computes the differences between the two times you pressed the _ now_ button in seconds. The `refDelta` variable is the same thing but with regards to the server clock. The time spent in sending the click operation to our backend is accounted for by adding the median time for communication accross 10 calls to the original click timestamp. 

I can provide you with all your measures if you come chat with us on crisp. 

Do let me know if you have other questions.

M.
