### ISSUE TITLE
Update about page

### ISSUE THREAD

**Issue by AlphonseJr** [Toolwatchapp/tw-backend#232]
At the bottom of the the first paragraph, we would like to add this sentence:

"One of our users has made a video on his YouTube channel explaining how to use Toolwatch: https://youtu.be/TvmQc6FTcDw?t=1m41s thanks Chris!"

Ideally we would embed a YouTube player (if this renders properly on the mobile app)

Thanks Hook!

**Comment by MathieuNls** [comment]
Done
